<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Article;
use AppBundle\Entity\Image;
use AppBundle\Form\ArticleEditType;
use AppBundle\Form\ArticleType;
use AppBundle\Form\ImageType;
use Cocur\Slugify\Slugify;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class ArticleController extends Controller
{
    public function addAction(Request $request)
    {
        $article = new Article();
        $articleForm = $this->createForm(ArticleType::class,$article);


        
        $articleForm->handleRequest($request);

        if($articleForm->isSubmitted() && $articleForm->isValid()){

            // $file stores the uploaded PDF file
            $file = $articleForm['image']->getData();

            $fileName = $article->getTitre().$file->getClientOriginalName().'.'.$file->guessExtension();

            $image = new Image();
            $image->setArticle($article);
            $image->setUrlImage($fileName);

           // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('url_image_article'),
                $fileName
            );

            $article->addImage($image);

            $article->setDateCreation(new \DateTime());
            $article->setUser($this->getUser());
            $article->setEstAccepte(false);
            $article->setEstArchive(false);

            $slugify = new Slugify();
            $slug=$slugify->slugify($article->getTitre().$article->getId());
            $article->setSlug($slug);

            #Enregistrement en base de donnees
            $em = $this->getDoctrine()->getManager();
            $em->persist($image);
            $em->persist($article);
            $em->flush();

            $this->addFlash("success","Article ajouté !");
            return $this->redirectToRoute("user_details");

        }

        return $this->render('article/ajouter_article.html.twig',[
            "articleForm"=>$articleForm->createView()
        ]);

    }

    public function detailAction($slug)
    {
        if(!$slug){
            throw $this->createNotFoundException("L'idée n'existe pas.");
        }

        $repo = $this->getDoctrine()->getRepository(Article::class);
        $article = $repo->findOneBySlug($slug);

        return $this->render('article/detail_article.html.twig', compact("article"));
    }

    public function modifierAction(Request $request, $slug){

        if(!$slug){
            throw $this->createNotFoundException("L'action n'existe pas.");
        }

        $repo = $this->getDoctrine()->getRepository(Article::class);
        $article = $repo->findOneBySlug($slug);


        $articleForm = $this->createForm(ArticleEditType::class,$article);

        $articleForm->handleRequest($request);

        if($articleForm->isSubmitted() && $articleForm->isValid()){

            $article->setEstAccepte(false);

            #Enregistrement en base de donnees
            $em = $this->getDoctrine()->getManager();
            $em->persist($article);
            $em->flush();

            $id = $article->getId();

            $this->addFlash("success","Article modifié !");
            return $this->redirectToRoute("article_detail",compact("slug"));

        }

        return $this->render('article/modifier_article.html.twig',[
            "articleForm"=>$articleForm->createView()
        ]);

    }


    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
