<?php

namespace AppBundle\Repository;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Méthode permettant de récuperer toutes les demandes sur les articles de la personne connectée
     *
     * @param $articles de la personne connectée
     *
     * @return $demandes correspondant aux articles en entrée
     *
     */
    public function findDemandes($articles){
        $ids = array();
        foreach($articles as $article){
            $ids[] = $article->getId();
        }

        //QueryBuilder pour recuperer toutes les actions qui correspondent à un article de l'utilisateur
        $qb = $this->createQueryBuilder('action');

        if (!empty($ids)) {
            $qb->join('action.article', 'article')
                ->addSelect('article')
                ->andWhere($qb->expr()->in('action.article', $ids))
                ->andWhere("action.estRefuse=0");
        }

        $query = $qb->getQuery();

        $demandes = $query->getResult();


        return $demandes;
    }
}
