<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Article;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAvecRecherche(Article $recherche){


        //QueryBuilder pour recuperer toutes les actions qui correspondent à un article de l'utilisateur
        $qb = $this->createQueryBuilder('article')
        ->andWhere("article.estAccepte = 1");
        
        if($recherche->getTaille()){

            $qb->andWhere("article.taille = :taille")
                ->setParameter('taille',$recherche->getTaille());

        }
        if($recherche->getType()){

            $qb->andWhere("article.type = :type")
                ->setParameter('type',$recherche->getType());

        }
        if($recherche->getMarque()){

            $qb->andWhere("article.marque = :marque")
                ->setParameter('marque',$recherche->getMarque());

        }
        if($recherche->getDescription()){
            $qb->andWhere('article.description LIKE \''. $recherche->getDescription() . '\'' );

        }
        if($recherche->getAVendre()){

            $qb->andWhere("article.aVendre = true");

        }

        $query = $qb->getQuery();

        $demandes = $query->getResult();


        return $demandes;
    }
}
