<?php

namespace AppBundle\Repository;

/**
 * EtatLieuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatLieuRepository extends \Doctrine\ORM\EntityRepository
{
}
