<?php

namespace AppBundle\Repository;

/**
 * RetourActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetourActionRepository extends \Doctrine\ORM\EntityRepository
{
}
