<?php

namespace AppBundle\Repository;

/**
 * TypeActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeActionRepository extends \Doctrine\ORM\EntityRepository
{
}
